# Generated by Django 6.0.2 on 2026-02-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_assessment_score', models.IntegerField(default=25)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='student', max_length=10)),
                ('assessment_marks', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('government_internships', models.TextField(blank=True, help_text='Details of government internships')),
                ('private_internships_jobs', models.TextField(blank=True, help_text='Details of private internships and jobs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('graduation_year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(limit_choices_to={'user_type': 'alumni'}, on_delete=django.db.models.deletion.CASCADE, to='network.profile')),
            ],
        ),
    ]
