# Generated by Django 6.0.2 on 2026-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('govt', 'Government'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
