# Generated by Django 6.0.2 on 2026-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='domain',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('other', 'Other')], default='software', max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stipend_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=10),
        ),
    ]
